quarkus:
  flyway:
    migrate-at-start: true
  datasource:
    db-kind: postgresql
    username: $DB_USERNAME
    password: $DB_PASSWORD
    jdbc:
      url: $DB_URL
  devservices:
    enabled: false
  hibernate-orm:
    database:
      generation: none
"%test":
  quarkus:
    log:
      console:
        json: false
    datasource:
      username: "quizzer"
      password: "quizpassword"
      jdbc:
        url: "jdbc:postgresql://localhost:5432/quizzes"
